language: python
dist: xenial
#addons:
#  artifacts: true
python:
  - "3.6"
  - "3.7"
  - "3.8"
cache: pip
before_install:
  - sudo apt-get -y install python-setuptools libwebp-dev
  - echo $TRAVIS_PYTHON_VERSION
  - pwd
install:
  - pip install -U coverage setuptools pyinstaller mypy
  - pip install -r requirements.txt
script:
  - mypy manga_py  # check syntax
  - coverage run run_tests.py
deploy:
  provider: pypi
  user: __token__
  password: $PYPI_KEY
  on:
    tags: true
    branch: master
    condition: $TRAVIS_PYTHON_VERSION == "3.7"
  skip_existing: true
